PUT http://localhost:8080/developer/4123
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillType": "FRONT_END",
  "experienceYear": 1,
  "memberId": "4123",
  "name": "정현수",
  "age": 20
}